travis:
  secure:
    BINSTAR_TOKEN: LkST1kRvm170IWTMaP8tPvQjVoOw9Nfbv4QTA8C0aUllgI5PZqe826ziu/LyygjsULuisKMZM7+EG09Wvaww9cfF2vHezdsPN51rVZFZ+WumPoUxsPyCrVvAfPsRcAepUFgdc5Mv5MAy4xmH28i+0IxnE0NLciONEPz6+yRUAqxooCaiBr+7zgbIk1VATf4ACRGb2/vrBmV8LokX2NDjYTXCJ79Oel9c3mu6ToGd5cMq+k1gKDXEIktoqaUhmqcg0v1m6AE9xOkGth/s+AXtiVdjiVMg2lZ5z03WWnRuie08PA63VOOv8KAmy9577DciCwFiu+9LlSHrSAS6Rzd5qxVzSDnCXW069zjo5K25r3eods6LfBQ7hbEsRBzxjG4yRTIZeZEWij66hj/4kLodXKJ+RlH0ysCkW70hIyoQMtC+1n+tCpJzykr/lTg168Iy3n5fvObCy28iCAvmgHHt+b2j7gkorA/P9d1JeOL/U9uaxoTw8F5eUfp8sZI6TK7/gPf9YdRDj7ryhCIqhcgE+hPv4xBwHo/KFeDN/i4XOWEBIXZjHFDZkRRPX5bshUoveXznrTMud/1OSjjeybyX8SeAYl8gBoitl8/UWAzdboL/7/GhfRXX8FmJNiDOWQrxgwnGrtoxQ2VptmQhnrYowjTUXQOP5JaoQrZIS+oXX8Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
