travis:
  secure:
    BINSTAR_TOKEN: uERwedj67u2b3Tfshe45T1PB9Biy0epIwSfZaxQkgx+E8f51dGtdu4hD6qorRv7C1kCE0YcPboT5S4nbAPN+CLJX4L8R5N3Euw0sxvUbL/7+Mhk8nPzLqwCCPYaLJf/WBE1D4Pc4jYy5DtTNuV/HEC8ThacEYBrYQarQ/HbWkayPdnqnIkx0V3dVJKSRYWXJ+wTBujnWRLK5K9Yc+rHKHWPWFZQbSSLJoW0Ny5+N78swqJex3GQahjwR43kvGV6w+V8olDklxfaQos5shV5pwTbxFCdvhFwi0Y4Uaeb8/7ZRQQ/dNn1Xqc/NI0trzdyhtKZxQ/liB/UJTHopR7fUrwVjS0IjANWaJYdrnOxTgxcC4oKNhRKyzDGlwBtU1ExHD4SCV5whzMTkKnFudnl5bLGas0bg6ORPgokJ+nQSN/eU0foeCTXG/xkuQzL5wGqO/s48kO3/o2dOFCAMeyF1DUOj7LjxS/ei/N6qntgO08rkS+IZCe7CaQDNPG8MUVfy2DNF09gunv/BgfOQTrKUWcpIXb9tgVH4AsQ/c5TfKyjohlmCWBgtMzCK+R4ZVP2T9y4GVZK3A/ZSRGo1ADk2mIMeE47tEObxWLFdpD/2O4QS3kDgGhm5dUUsADsK+Og+DgIWuj0HFoqIsFtedRGlMKP3xgwmmQXDvXtXghZ1NiM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
